### ISSUE TITLE
EOS.undent is deprecated

### ISSUE THREAD

**Issue by leancode** [leedm777/homebrew-asterisk#28]
Here is what I get: So far it seems to continue the install but it does say to report this so here we go.
==> Installing leedm777/asterisk/pjsip-asterisk
==> Downloading http://pjsip.org/release/2.7.1/pjproject-2.7.1.tar.bz2
######################################################################## 100.0%
==> Patching
patching file pjmedia/build/Makefile
patching file pjsip/build/Makefile
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/leedm777/homebrew-asterisk/pjsip-asterisk.rb:92:in `install'
Please report this to the leedm777/asterisk tap!

**Comment by YuriiKhomych** [comment]
Hi!
I have the same issue.

brew install asterisk

==> Installing asterisk from leedm777/asterisk
Warning: leedm777/asterisk/asterisk 15.1.5 is available and more recent than version 15-devel.
==> Installing dependencies for leedm777/asterisk/asterisk: pjsip-asterisk, libogg, speex
==> Installing leedm777/asterisk/asterisk dependency: pjsip-asterisk
==> Downloading http://pjsip.org/release/2.7.1/pjproject-2.7.1.tar.bz2
Already downloaded: /Users/yuriikhomych/Library/Caches/Homebrew/pjsip-asterisk-2.7.1.tar.bz2
==> Patching
patching file pjmedia/build/Makefile
patching file pjsip/build/Makefile
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/leedm777/homebrew-asterisk/pjsip-asterisk.rb:92:in `install'
Please report this to the leedm777/asterisk tap!
Or, even better, submit a PR to fix it!

**Comment by visomi-dev** [comment]
this issue is solved with the pull request #29

**Comment by alisajjad** [comment]
Hi
     i am facing the same issue
*********************--------------****************
==> Installing asterisk from leedm777/asterisk
==> Installing dependencies for leedm777/asterisk/asterisk: pjsip-asterisk, libogg, speex
==> Installing leedm777/asterisk/asterisk dependency: pjsip-asterisk
==> Downloading http://pjsip.org/release/2.7.1/pjproject-2.7.1.tar.bz2
Already downloaded: /Users/sajjadali/Library/Caches/Homebrew/pjsip-asterisk-2.7.1.tar.bz2
==> Patching
patching file pjmedia/build/Makefile
patching file pjsip/build/Makefile
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/leedm777/homebrew-asterisk/pjsip-asterisk.rb:92:in `install'
Please report this to the leedm777/asterisk tap!
Or, even better, submit a PR to fix it!
*********************--------------****************
Need help please
